server:
  port: 8082

spring:
  application:
    name: scene-service

device:
  service:
    url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
